# Generated by Django 2.2.1 on 2021-08-28 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Номер ответа',
                'verbose_name_plural': 'Номера ответов',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Наименование опроса')),
                ('description', models.CharField(max_length=255, verbose_name='Описание опроса')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала опроса')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания опроса')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'ordering': ['-start_date'],
                'permissions': [('elapse_date', 'Опрос - начался!')],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('type', models.CharField(choices=[('1', 'Текст'), ('2', 'Выбор'), ('3', 'Опция')], default='1', max_length=1, verbose_name='Тип ответа')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='interview.Category', verbose_name='Наименование опроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант ответа')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='interview.Question')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='Ответ Текстом')),
                ('answer_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_choice', to='interview.Choice')),
                ('answer_multi', models.ManyToManyField(blank=True, related_name='answer_multi', to='interview.Choice')),
                ('answer_numbers', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interview.AnswerNumber')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.Category')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.Question')),
            ],
            options={
                'verbose_name': 'Ответы пользователя',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
    ]
