# Generated by Django 2.2.1 on 2021-08-18 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-start_date'], 'permissions': [('elapse', 'Опрос - начался!')], 'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
    ]
