# Generated by Django 2.2.1 on 2021-08-18 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20210818_0557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-start_date'], 'permissions': [('elapse_date', 'Опрос - начался!')], 'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
    ]
