# Generated by Django 2.2.1 on 2021-08-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_auto_20210826_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answernumber',
            name='number',
            field=models.IntegerField(default=range(100000, 999999), unique=True),
        ),
    ]
