# Generated by Django 2.2.1 on 2021-08-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_auto_20210826_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answernumber',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
