# Generated by Django 2.2.1 on 2021-08-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_auto_20210826_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answernumber',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
