# Generated by Django 2.2.1 on 2021-08-26 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_auto_20210826_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_numbers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='interview.AnswerNumber'),
        ),
        migrations.AlterField(
            model_name='answernumber',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
