# Generated by Django 2.2.1 on 2021-08-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_auto_20210826_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice',
        ),
    ]
