# Generated by Django 2.1.1 on 2021-07-19 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='AnswerChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_choices', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerChoiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerchoicetype_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование выбора')),
                ('answerchoicetype_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.AnswerChoices')),
            ],
            options={
                'verbose_name': 'Ответ выбором',
                'verbose_name_plural': 'Ответы выбором',
            },
        ),
        migrations.CreateModel(
            name='AnswerMulties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_multi', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerMultiType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answermultitype_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование выбора')),
                ('answermultitype_choice', models.ManyToManyField(to='polls.AnswerMulties')),
            ],
            options={
                'verbose_name': 'Ответ опция',
                'verbose_name_plural': 'Ответы опцией',
            },
        ),
        migrations.CreateModel(
            name='AnswerText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answertexttype_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование выбора')),
                ('answertypetype_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.AnswerChoices')),
            ],
            options={
                'verbose_name': 'Ответ-текст',
                'verbose_name_plural': 'Ответы текстом',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_poll', models.CharField(max_length=255, verbose_name='Наименование опроса')),
                ('pubdate_poll', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('public_poll', models.BooleanField(default=False, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('type_answer', models.CharField(choices=[('1', 'Текст'), ('2', 'Выбор'), ('3', 'Опция')], max_length=1, verbose_name='Вариант ответа')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll', verbose_name='Наименование опроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.AnswerChoices')),
                ('user_answer_text', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Answer')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('user_poll', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Poll')),
                ('user_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_choice_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.AnswerChoices', verbose_name='Выбор'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_multi_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.AnswerMulties', verbose_name='Мульти'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_text_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.AnswerText'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
