# Generated by Django 2.1 on 2021-07-30 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Варианты ответа')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_poll', models.CharField(max_length=255, verbose_name='Наименование опроса')),
                ('description_poll', models.CharField(max_length=255, verbose_name='Описание опроса')),
                ('start_date_poll', models.DateField(blank=True, null=True, verbose_name='Дата начала опроса')),
                ('end_date_poll', models.DateField(blank=True, null=True, verbose_name='Дата окончания опроса')),
                ('owner_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_polls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'ordering': ['-start_date_poll'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('type_question', models.CharField(choices=[('1', 'Текст'), ('2', 'Выбор'), ('3', 'Опция')], default='1', max_length=1, verbose_name='Тип ответа')),
                ('poll_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_poll', to='polls.Poll', verbose_name='Наименование опроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer_text', models.TextField(blank=True, null=True, verbose_name='Ответ Текстом')),
                ('user_answer_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='polls.AnswerChoice')),
                ('user_answer_multi', models.ManyToManyField(blank=True, related_name='_useranswer_user_answer_multi_+', to='polls.AnswerChoice')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('user_poll', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Poll')),
                ('user_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Question')),
            ],
            options={
                'verbose_name': 'Ответы пользователя',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
        migrations.AddField(
            model_name='answerchoice',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.Question'),
        ),
    ]
