# Generated by Django 2.1.1 on 2021-07-19 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_multi_type',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_multi_type',
            field=models.ManyToManyField(blank=True, to='polls.AnswerMulties', verbose_name='Мульти'),
        ),
        migrations.RemoveField(
            model_name='answermultitype',
            name='answermultitype_choice',
        ),
        migrations.AddField(
            model_name='answermultitype',
            name='answermultitype_choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.AnswerMulties'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answertext',
            name='answertypetype_choice',
            field=models.TextField(),
        ),
    ]
