# Generated by Django 2.1.1 on 2021-07-19 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210719_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_multi_type',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_multi_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.AnswerMulties', verbose_name='Мульти'),
        ),
    ]
