# Generated by Django 2.1.1 on 2021-07-19 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210719_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_text_type',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_answer_multi',
            field=models.ManyToManyField(to='polls.AnswerMultiType'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.AnswerChoiceType'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user_answer_text',
            field=models.TextField(verbose_name='Ответ Текстом'),
        ),
        migrations.DeleteModel(
            name='AnswerText',
        ),
    ]
